# Compose file for launching the test setup with
# a Peer for Acme and a Peer for Budget

version: '2'

networks:
  automobile:

# Storage outside the containers
volumes:
  data-orderer.excise.com:
  data-peer1.excise.com:
  data-peer1.fbr.com:
  data-peer1.manufacturer.com:

services:

  # Orderer service
  orderer.excise.com:
    container_name: orderer.excise.com
    image: hyperledger/fabric-orderer:$IMAGE_TAG
    command: orderer
    # Override environment variables for orderer in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=ERROR
    # Host folder mappings
    volumes:
    # Folder with genesis block
    - ${PWD}/config/orderer:/var/hyperledger/config
    # Map the folder with MSP for orderer
    - ${PWD}/config/crypto-config/ordererOrganizations/excise.com/orderers/orderer.excise.com/msp:/var/hyperledger/msp
    # Added to support the TLS setup
    - ${PWD}/config/crypto-config/ordererOrganizations/excise.com/orderers/orderer.excise.com/tls:/var/hyperledger/tls
    - data-orderer.excise.com:/var/ledger
    ports:
      - 7050:7050
    networks:
      - automobile

  # Excise peer1
  peer1.excise.com:
    container_name: peer1.excise.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # Override variables in this section
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_automobile
    # Start the peer node
    command: peer node start
    # Host folder mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/config/excise:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/config/crypto-config/peerOrganizations/excise.com/peers/peer1.excise.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/config/crypto-config/peerOrganizations/excise.com/peers/peer1.excise.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.excise.com:/var/hyperledger/production
    depends_on: 
      - orderer.excise.com
    # Map the ports on Host VM to container ports
    ports:
      - 7055:7055
      - 7052:7052
    networks:
      - automobile

  # Fbr peer1
  peer1.fbr.com:
    container_name: peer1.fbr.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # landing directory
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
    # Environment setup for peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - GOPATH=/opt/gopath
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_automobile
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.fbr.com:7051
    # host file system mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/config/fbr:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/config/crypto-config/peerOrganizations/fbr.com/peers/peer1.fbr.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/config/crypto-config/peerOrganizations/fbr.com/peers/peer1.fbr.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.fbr.com:/var/hyperledger/production
    depends_on: 
      - orderer.excise.com
    # Map the ports on Host VM to container ports
    ports:
      - 8060:7060
      - 8052:7052
    networks:
      - automobile

  # Manufacturer peer1
  peer1.manufacturer.com:
    container_name: peer1.manufacturer.com
    image: hyperledger/fabric-peer:$IMAGE_TAG
    # landing directory
    working_dir: $HOME
    # command: peer node start --peer-chaincodedev=true
    command: peer node start
    # Environment setup for peer
    environment:
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
      - GOPATH=/opt/gopath
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${COMPOSE_PROJECT_NAME}_automobile
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.manufacturer.com:7051
    # host file system mappings
    volumes:
      # Folder with channel create tx file
      - ${PWD}/config/manufacturer:/var/hyperledger/config
      # Map the folder with MSP for Peer
      - ${PWD}/config/crypto-config/peerOrganizations/manufacturer.com/peers/peer1.manufacturer.com/msp:/var/hyperledger/msp
      # Added to support the TLS setup
      - ${PWD}/config/crypto-config/peerOrganizations/manufacturer.com/peers/peer1.manufacturer.com/tls:/var/hyperledger/tls
      - /var/run/:/var/run/
      - data-peer1.manufacturer.com:/var/hyperledger/production
    depends_on: 
      - orderer.excise.com
    # Map the ports on Host VM to container ports
    ports:
      - 8065:7065
      - 9052:7052
    networks:
      - automobile

  # Tools container used for managing peers
  tools:
    container_name: tools
    command: /bin/bash

    # Tools container image
    image: hyperledger/fabric-tools:$IMAGE_TAG

    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - FABRIC_CFG_PATH=/var/hyperledger/config
      - FABRIC_LOGGING_SPEC=WARNING
    # This is the working directory on login
    working_dir: /opt/scripts
    volumes:
      # Mapping for the sample chaincode folders
      - ${PWD}/../artefacts/nodechaincode:/opt/nodechaincode
      - ${PWD}/../gopath:/opt/gopath
      # Folder with channel create tx file
      - ${PWD}/config:/var/hyperledger/config
      # Map the folder to root of all Fabric CA Client crypto
      - ${PWD}/config/crypto-config/peerOrganizations:/var/hyperledger/crypto
      # VM docker stream folder mapping
      - /var/run/:/host/var/run/
      # Map the bins folder
      - ${PWD}/tool-bins:/opt/scripts
    networks:
      - automobile
  
  